### ISSUE TITLE
"pip install scikit-image" fails in a new virtualenv

### ISSUE THREAD

**Issue by blueyed** [scikit-image/scikit-image#1329]
`pip install scikit-image` fails to install the dependencies (numpy and six) - for numpy with `ImportError: No module named numpy.distutils.core`.

I have seen #1040 and #1042, but this does not it - is it supposed to do so?

It works when installing numpy and six manually.

I came here from/via `pip install paperwork`, which also has `numpy` as its dependency, and it got installed:

        [...]
        Installed /tmp/pip-build-5gdxQQ/scipy/.eggs/numpy-1.9.1-py2.7-linux-x86_64.egg
    [...]
    Downloading/unpacking scikit-image (from paperwork)
      Downloading scikit-image-0.10.1.tar.gz (16.7MB): 16.7MB downloaded
      Storing download in cache at ./.cache/pip/download/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fs%2Fscikit-image%2Fscikit-image-0.10.1.tar.gz
      Running setup.py (path:/home/user/.local/venvs/paperwork/build/scikit-image/setup.py) egg_info for package scikit-image
        Traceback (most recent call last):
          File "<string>", line 17, in <module>
          File "/home/user/.local/venvs/paperwork/build/scikit-image/setup.py", line 37, in <module>
            from numpy.distutils.core import setup
        ImportError: No module named numpy.distutils.core
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):

      File "<string>", line 17, in <module>

      File "/home/user/.local/venvs/paperwork/build/scikit-image/setup.py", line 37, in <module>

        from numpy.distutils.core import setup

    ImportError: No module named numpy.distutils.core

I've seen it mentioned in the readme/wiki: https://github.com/jflesch/paperwork/blob/stable/doc/install.debian.markdown#runtime-dependencies

**Comment by blink1073** [comment]
Closing, as it is fixed in master and will be in v0.11.

**Comment by luismasuelli** [comment]
Still fails!!

(mybrandnewvenv)me@my-machine:~$ pip install scikit-image
Downloading/unpacking scikit-image
  Downloading scikit-image-0.11.3.tar.gz (18.6MB): 18.6MB downloaded
  Running setup.py (path:/home/me/.virtualenvs/mybrandnewvenv/build/scikit-image/setup.py) egg_info for package scikit-image
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/me/.virtualenvs/mybrandnewvenv/build/scikit-image/setup.py", line 76, in <module>
        from numpy.distutils.core import setup
    ImportError: No module named numpy.distutils.core
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/home/me/.virtualenvs/mybrandnewvenv/build/scikit-image/setup.py", line 76, in <module>
    from numpy.distutils.core import setup
ImportError: No module named numpy.distutils.core

**Comment by stefanv** [comment]
This is a bug in our implementation of setup.py.  We borrowed incorrectly from scipy!

**Comment by blink1073** [comment]
This is fixed in master: https://github.com/scikit-image/scikit-image/blob/master/setup.py#L76

**Comment by JDWarner** [comment]
As far as I can tell, @blink1073 is right and this is fixed. The last traceback posted is from an attempted install of 0.11.3, not source. Closing, but feel free to reopen if this is still present in 0.12

**Comment by stefanv** [comment]
I dug through the source code of our setup, and I think we can still improve it.  ``scipy`` makes use of the ``build_requires`` parameter to add numpy to packages to be installed.

**Comment by blink1073** [comment]
I looked at what they were doing, and the only differences I could see where a special case for building wheels, which we do separately, and support for distutils, (we require setuptools).

**Comment by stefanv** [comment]
Don't we raise an error if numpy is not installed? I don't recall scipy
doing that, but I may be mistaken.

**Comment by blink1073** [comment]
This line will raise an `ImportError`: https://github.com/scipy/scipy/blob/master/setup.py#L253, we instead show a more specific message: https://github.com/scikit-image/scikit-image/blob/master/setup.py#L100

**Comment by stefanv** [comment]
So is the logic that egg_info will run first, get the numpy dependency,
install it, and then continue?  I should try this in a clean environment
later today to see what happens.

**Comment by blink1073** [comment]
Yes, that is my understanding.

**Comment by serser** [comment]
`pip install scikit-image==0.18.1` fails, down to `0.17.1` okay.

**Comment by hmaarrfk** [comment]
@serser happy to hear you are using scikit-image and trying the new version.

We would be interested in understanding why your particular situation failed.

Unfortunately, this issue is quite old as it was first opened in 2014 and quite a bit has changed.

If you need extra assistance, I would suggest opening an other issue and including the resquested information!
