### ISSUE TITLE
Failing test - AssertionError

### ISSUE THREAD

**Issue by ashkurti** [scikit-image/scikit-image#1668]
Any idea on how to fix this:
```
======================================================================
FAIL: skimage.measure.tests.test_fit.test_ransac_geometric
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "skimage/measure/tests/test_fit.py", line 185, in test_ransac_geometric
    assert np.all(np.nonzero(inliers == False)[0] == outliers)
AssertionError

----------------------------------------------------------------------
```

**Comment by emmanuelle** [comment]
I looked at it with @ashkurti  and it seems that some additional outliers were detected, sounds like a real bug.

**Comment by emmanuelle** [comment]
@ashkurti the test passes on my laptop. If you have the time, we should get together at some point and see what happens to the different points and what is the difference on your computer and on mine.

**Comment by ashkurti** [comment]
Yes @emmanuelle lets check this together today, I will be around most of the day.

**Comment by ashkurti** [comment]
@emmanuelle I just ran the tests again twice with the respective difference at test_ransac_geometric().
1. The test failed - using ``` model_est, inliers = ransac((src, dst), AffineTransform, 2, 20)```
2. The test passed - using ``` model_est, inliers = ransac((src, dst), AffineTransform, 4, 20)```

**Comment by ahojnnes** [comment]
@ashkurti Thanks for tracking it down. This should be fixed in the test case, as an affine transform needs at least 3 samples. Nevertheless the RANSAC function shouldn't crash.

**Comment by emmanuelle** [comment]
@ahojnnes the RANSAC function does not crash, it's just that the test fails. Then I guess the test should be modified to use 3 samples? I still don't understand why the test passes on my machine and not on the one of @ashkurti, but if the test does not make sense, let's change it.

**Comment by ahojnnes** [comment]
Maybe due to a different PRNG? But it should be consistent across machines...

**Comment by emmanuelle** [comment]
We took some time with @ashkurti to check that the same points were generated on her machine and on mine for ``src``, and that the same indices are chosen in the for loop inside the RANSAC function, so I don't think we can blame the PRNG...

**Comment by ahojnnes** [comment]
Different Numpy versions?

**Comment by emmanuelle** [comment]
Maybe... what is your numpy version, @ashkurti ? I'm using 1.8.2

**Comment by ashkurti** [comment]
@emmanuelle and @ahojnnes  numpy 1.9.2 with python version 2.7.6.

**Comment by ahojnnes** [comment]
There we go. Any chance for either of you to test the other one's Numpy version?
