### ISSUE TITLE
ValueError exception in measure/_regionprops

### ISSUE THREAD

**Issue by nelzas** [scikit-image/scikit-image#2625]
## Description
[Please provide a general introduction to the issue/proposal.]
I've encountered a few times the exception ValueError while working with region properties.
I've delved into it a little, and I think the root cause is due to floating point errors.
After some time debugging, I've reduced it to a small example code that is later down.
It happens sometimes when accessing minor_axis_length. It tries to take the sqrt of a negative number.
from scikit-image code:
```python
    def minor_axis_length(self):
        _, l2 = self.inertia_tensor_eigvals
        return 4 * sqrt(l2)
```
in my example below l2 is negative but very close to zero (-8.8817841970012523e-16).
It is the result of the following calculation:
```python
        l2 = (a + c) / 2 - sqrt(4 * b ** 2 + (a - c) ** 2) / 2
```
For the numbers I got while debugging, the math on paper gives zero but here I got a very small negative number.

I'll be happy to try to fix it myself, but currently I have no clue how to approach this. So if you want to give me advice, I can try to work on this, and if you prefer to handle this, that's fine :-)

[If reporting a bug, attach the entire traceback from Python.]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/skimage/measure/_regionprops.py", line 84, in func2d
    return method(self, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/skimage/measure/_regionprops.py", line 232, in minor_axis_length
    return 4 * sqrt(l2)
ValueError: math domain error
```
## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example
Here is a relatively short example reproducing the error, comments shows outputs.
```python
import numpy as np
from skimage import measure

a = np.zeros((350, 350), np.uint8)
a.nonzero()
# (array([], dtype=int64), array([], dtype=int64))
a[321, 86] = 1
a[322, 90] = 1
a[323, 94] = 1
a.nonzero()
# (array([321, 322, 323]), array([86, 90, 94]))
p = measure.regionprops(a)
for i in range(len(p)):
    print(i, p[i].inertia_tensor_eigvals)
# 0 (11.333333333333332, -8.8817841970012523e-16)
p[0].minor_axis_length
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/opt/conda/lib/python3.6/site-packages/skimage/measure/_regionprops.py", line 84, in func2d
#     return method(self, *args, **kwargs)
#   File "/opt/conda/lib/python3.6/site-packages/skimage/measure/_regionprops.py", line 232, in minor_axis_length
#     return 4 * sqrt(l2)
# ValueError: math domain error
```

- [ ] Relevant images (if any)
- [ ] Operating system and version
Linux Debian 3.16.0-4-amd64 - and on this used docker image kaggle/python (https://hub.docker.com/r/kaggle/python/)
- [ ] Python version
3.6.0
- [ ] scikit-image version (run `skimage.__version__`)
both 0.12.3 and 0.13.0

**Comment by soupault** [comment]
Hello @nelzas , thanks for reporting!

I can reproduce the issue with the latest Python 3.6, `numpy`, `skimage`.

**Comment by soupault** [comment]
>Do you think it's something someone who have not worked on skimage code can handle? with some mentoring?
If you can point to a direction, I'm ready to try.

@nelzas This should be relatively easy to fix, at least in a dirty way (appying `max(l2, 0)`).

At the same time, there is a PR with a massive refactoring of moments' computation (see
https://github.com/scikit-image/scikit-image/pull/2603/files#diff-9ad80e81791ed23620983b83431fabf2R200). Potentially, the issue is fixed there :). My opinion would be to jump straight away to that PR.

In the meantime, I think, you could fork the library and fix the issue in you repo. Should be quite easy to do using the method above.
The issue will stay opened, and we'll keep you posted on the updates.

**Comment by nelzas** [comment]
Thanks for the quick reply.

@nelzas <https://github.com/nelzas> This should be relatively easy to fix,
> at least in a dirty way (appying max(l2, 0)).
>
I can do that :-)

> At the same time, there is a PR with a massive refactoring of moments'
> computation (see
> https://github.com/scikit-image/scikit-image/pull/2603/files#diff-
> 9ad80e81791ed23620983b83431fabf2R200). Potentially, the issue is fixed
> there :). My opinion would be to jump straight away to that PR.
>
I'll look into the PR and check. If the issue is fixed there, I'll let you
know.


> In the meantime, I think, you could fork the library and fix the issue in
> you repo. Should be quite easy to do using the method above.
> The issue will stay opened, and we'll keep you posted on the updates.
>
I apologize if I mislead you into thinking I was pushing for an urgent fix.
I just wanted to help.
For the problem in the codebase I was working on, I just added, to our
code, a "try... except..." clause and in the exception I set the result to
zero without having to modify the skimage.

**Comment by soupault** [comment]
>I apologize if I mislead you into thinking I was pushing for an urgent fix.
I just wanted to help.
For the problem in the codebase I was working on, I just added, to our
code, a "try... except..." clause and in the exception I set the result to
zero without having to modify the skimage.

No-no, I mean we could do that as well, if it is a justified fix.
It is just my personal attitude not to put any stones on the way of complicated PRs which are already work-in-progress.
We will have this fixed by 0.14, in any case.

**Comment by nelzas** [comment]
Indeed the PR mentioned above solve the issue for my test case :-)

**Comment by soupault** [comment]
Occasionally fixed via #2603.

**Comment by petsuter** [comment]
A similar problem still exists / re-appeared: https://github.com/scikit-image/scikit-image/issues/6630
