### ISSUE TITLE
`IOError: cannot write mode RGBA as JPEG` when using PIL plugin

### ISSUE THREAD

**Issue by yarikoptic** [scikit-image/scikit-image#2843]
interested since with PIL 4.2.1 , the 0.13.1 fails with 
```

======================================================================
ERROR: skimage.novice.tests.test_novice.test_update_on_save
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/skimage-0.13.1/debian/tmp/usr/lib/python2.7/dist-packages/skimage/novice/tests/test_novice.py", line 159, in test_update_on_save
    pic.save(filename)
  File "/build/skimage-0.13.1/debian/tmp/usr/lib/python2.7/dist-packages/skimage/novice/_novice.py", line 329, in save
    io.imsave(path, self.array)
  File "/build/skimage-0.13.1/debian/tmp/usr/lib/python2.7/dist-packages/skimage/io/_io.py", line 133, in imsave
    return call_plugin('imsave', fname, arr, plugin=plugin, **plugin_args)
  File "/build/skimage-0.13.1/debian/tmp/usr/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "/build/skimage-0.13.1/debian/tmp/usr/lib/python2.7/dist-packages/skimage/io/_plugins/pil_plugin.py", line 260, in imsave
    img.save(fname, format=format_str, **kwargs)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1893, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python2.7/dist-packages/PIL/JpegImagePlugin.py", line 604, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
IOError: cannot write mode RGBA as JPEG

```
while master passes.... anyone remembers if there was a fix to pick up into the debian package of the 0.13.1?

**Comment by soupault** [comment]
@yarikoptic I don't remember anything on this kind.
`skimage.novice` is now deprecated (see https://github.com/scikit-image/scikit-image/pull/2784), but we should consider updating our PIL plugin, it seems.

**Comment by stefanv** [comment]
Novice should check for RGBA images, and not try to write them to JPEG.

**Comment by hmaarrfk** [comment]
This seems to have been fixed in #2706. Since 0.14 has been released, maybe we can close this?

**Comment by jni** [comment]
The error still happens on master (RGBA cannot be written to JPG), but I would argue that it would be hard to write a better error, and novice is deprecated (so we won't be doing this internally anymore) so yes, let's close this.
