### ISSUE TITLE
language settings on PyPI

### ISSUE THREAD

**Issue by jarrodmillman** [scikit-image/scikit-image#4234]
## Description

I noticed something strange on the skimage PyPI site:
https://pypi.org/project/scikit-image/

For instance, where I expect it to say `Project links` it says `プロジェクトのリンク`.  Is anyone else seeing that?

**Comment by jarrodmillman** [comment]
It seem fixed now.

**Comment by soupault** [comment]
I still see the issue, but there is probably nothing we can do.
